name: fantastico_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+5
  collection: ^1.17.1
  crypto: ^3.0.3
  equatable: ^2.0.5
  fantastico_api_client:
    path: packages/fantastico_api_client
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.4
  go_router: ^11.1.2
  google_mlkit_barcode_scanning: ^0.9.0
  intl: ^0.18.0
  package_info_plus: ^4.2.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/brands/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
