include: package:very_good_analysis/analysis_options.5.0.0.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: false
    strict-inference: false

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    avoid_positional_boolean_parameters: false
    only_throw_errors: false
